### ISSUE TITLE
[Suggestion] 1.20.1 version ready for 1.4

### ISSUE THREAD

**Issue by gdadamx** [WinterWolfSV/Cobblemon_Quests#1]
Hey, your mod is exactly what i need, but unfortunately i'm using 1.20.1 snapshot. Anyway, that's just a suggestion, not a critic or a demand and you can totally close the issue if needed.

Many are using the snapshot and I would love to see your mod as a pioneer and you should post at Cobblemon's discord too.
Have a good day :)

**Comment by WinterWolfSV** [comment]
Hey! I appreciate your feedback and have ported the mod to 1.20.1. The latest version can be found on my modrinth page: https://modrinth.com/mod/cobblemon-quests/versions
I hope everything works as it should on your server!
