### ISSUE TITLE
Quests Not Working

### ISSUE THREAD

**Issue by greglor** [WinterWolfSV/Cobblemon_Quests#1]
I have set up quests for defeating and catching Pokemon, and whenever I catch or defeat a Pokemon it just doesn't add to the count. Also, whenever I defeat a Pokemon, a message appears in chat saying something went wrong. Not sure if it's something I'm doing wrong or not.

![image](https://github.com/WinterWolfSV/Cobblemon_Quests/assets/68510665/9b9b5985-0463-4852-b924-9143afa43f42)

(This is in the Most Recent Version of the Mod)

**Comment by WinterWolfSV** [comment]
Hey! I apologize for the delay in my response. The error message you're having isn't related to the Cobblemon Quests mod. Although, that the Quests aren't updating does appear strange. Would you mind sharing the latest log where you do these three steps:
- Create two Cobblemon tasks, one that is for defeating and one that is for catching a pokemon 
- Catch and defeat a pokemon
- Share the full log (should be named latest.log)

**Comment by greglor** [comment]
will get on this asap

the weird thing abt the message is that it only appears when i have a “defeat x pokémon” quest active so i assumed it had something to do with cobblemon quests

**Comment by greglor** [comment]
[latest.log](https://github.com/WinterWolfSV/Cobblemon_Quests/files/12920418/latest.log)

Sorry it's v large and might be confusing i have a lot of other mods lol

**Comment by WinterWolfSV** [comment]
Hey! Sorry about my previous assumptions. After looking at your log and trying for a good hour, I haven't been able to successfully replicate the issues you're experiencing. It seems as if the mod is trying to read data that doesn't exist, and that leads me to believe that the issue might be related to some other mod that interferes. I know it is a lot of work and such, but my suggestion would be that you perform a binary search (Remove half of the mods except for the cobblemon and ftb quest mods and their dependencies, check if it works, and repeat until you've found the mod that causes incompatibilities). If you do end up finding it, I could check to see if I am able to find a solution to it!

**Comment by greglor** [comment]
okay ill lyk, thx

**Comment by greglor** [comment]
Hey again! Lol it's been a month but I just wanted to give an update. It seems like the quests work in only certain worlds of mine. So I was wondering, do the quests depend on certain gamerules to be enabled or disabled? Maybe the world that isn't working has a certain gamerule off that is making it not work?
