### ISSUE TITLE
Quest Action "Defeat" Isn't updating values after instance

### ISSUE THREAD

**Issue by Tolberto** [WinterWolfSV/Cobblemon_Quests#10]
I have a few quest lines built that involve defeating specific types or just a certain number of Pokémon that are not being kept up. Value stays at 0 for all "defeat" quests regardless of the dependencies completed or no dependency. I have tested battling for a pure count and if a battle a specified type, same issues

Not as familiar with the process of checking the pathways for this, but just wanted to see if this was a bug or if I'm missing a prerequisite for these to update.

Current versions of dependent mods 
cobblemon-quests - 1.1.10
ftb-library 2001.2.2
ftb-quests 2001.4.6
ftb-teams 2001.3.0
Cobblemon-fabric 1.5.2
Architectury-fabric 9.2.14

**Comment by Dupercane1** [comment]
im having the same issue after updating to cobblemon 1.5.

**Comment by Tolberto** [comment]
These are the server errors for those that have the knowledge to chase down the issue

WARNING: Error processing task for team 
[
winterwolfsv.cobblemon_quests.tasks.CobblemonTask.CobblemonTaskIncrease(CobblemonTask.java:316), 
winterwolfsv.cobblemon_quests.events.FTBCobblemonEventHandler.processTasksForTeam(FTBCobblemonEventHandler.java:311), 
winterwolfsv.cobblemon_quests.events.FTBCobblemonEventHandler.pokemonBattleVictory(FTBCobblemonEventHandler.java:139), 
com.cobblemon.mod.common.api.reactive.ObservableSubscription.handle(ObservableSubscription.java:16), 
com.cobblemon.mod.common.api.reactive.SimpleObservable.emit(SimpleObservable.java:39), 
com.cobblemon.mod.common.battles.interpreter.instructions.WinInstruction$invoke$2.invoke(WinInstruction.java:78), 
com.cobblemon.mod.common.battles.interpreter.instructions.WinInstruction$invoke$2.invoke(WinInstruction.java:68), 
com.cobblemon.mod.common.api.battles.model.PokemonBattle$dispatchGo$1.invoke(PokemonBattle.java:344), 
com.cobblemon.mod.common.api.battles.model.PokemonBattle$dispatchGo$1.invoke(PokemonBattle.java:343), 
com.cobblemon.mod.common.api.battles.model.PokemonBattle.dispatch$lambda$53(PokemonBattle.java:333), 
com.cobblemon.mod.common.api.battles.model.PokemonBattle.tick(PokemonBattle.java:383), 
com.cobblemon.mod.common.battles.BattleRegistry$tick$1.invoke(BattleRegistry.java:238), 
com.cobblemon.mod.common.battles.BattleRegistry$tick$1.invoke(BattleRegistry.java:238), 
com.cobblemon.mod.common.battles.BattleRegistry.tick$lambda$10(BattleRegistry.java:238), 
java.base/java.util.concurrent.ConcurrentHashMap$ForEachValueTask.compute(ConcurrentHashMap.java:5027), 
java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754), 
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373), 
java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686), 
java.base/java.util.concurrent.ConcurrentHashMap.forEachValue(ConcurrentHashMap.java:4057), 
com.cobblemon.mod.common.battles.BattleRegistry.tick(BattleRegistry.java:238), 
com.cobblemon.mod.common.events.ServerTickHandler.onTick(ServerTickHandler.java:21), 
com.cobblemon.mod.common.Cobblemon$initialize$7.invoke(Cobblemon.java:368), 
com.cobblemon.mod.common.Cobblemon$initialize$7.invoke(Cobblemon.java:368), 
com.cobblemon.mod.common.api.reactive.ObservableSubscription.handle(ObservableSubscription.java:16), 
com.cobblemon.mod.common.api.reactive.SimpleObservable.emit(SimpleObservable.java:39), 
com.cobblemon.mod.fabric.CobblemonFabric.initialize$lambda$8(CobblemonFabric.kt:440), 
net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43), 
net.minecraft.server.MinecraftServer.handler$zkm000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:3362), 
net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847), net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671), 
net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265), java.base/java.lang.Thread.run(Thread.java:840)
]

**Comment by Dupercane1** [comment]
I DMd the author on discord and he told me this: 

Hey! Unfortunately there's no easy way of back porting the quests to the old version, but if you don't mind messing with config files you could manually edit the quest files. The changes made are that "any_choice" is replaced by whitespace, the target entity has changed its name in the config file, you're not able to select multiple Pokémon or traits, and possibly some other changes as well. I'd recommend looking at two config files from the different versions (located somewhere in config/ftbquests/chapters iirc) and making the appropriate changes

**Comment by WinterWolfSV** [comment]
Fixed in version 1.1.11
