### ISSUE TITLE
Quest Action "Defeat" Isn't Working

### ISSUE THREAD

**Issue by Milotic609** [WinterWolfSV/Cobblemon_Quests#11]
Havent updated it from 1.4 to 1.5, I directly Installed the newer version and it doesnt work at all 
Also I dont know if you are reading this but it would be cool to add more forms or a way to add a tag so it works on other regional pokemon from addons 
Like the Craftonian Forms on a config file or something
Thank you!

**Comment by WinterWolfSV** [comment]
FIxed in version 1.1.11
