### ISSUE TITLE
The game didn't show me any missions :( not even the quests( they are the same xD)

### ISSUE THREAD

**Issue by RoshbyHDZ** [WinterWolfSV/Cobblemon_Quests#13]
![image](https://github.com/user-attachments/assets/8867a3cf-9855-45f1-ba71-2ee6eff49f5c)

**Comment by RoshbyHDZ** [comment]
and I will show you the mods that I have
![image](https://github.com/user-attachments/assets/cf95d8ff-a289-4036-aa98-5dcb4bb986e8)

**Comment by WinterWolfSV** [comment]
The mod adds the ability for quest creators to create quests. It does not add quests to the game itself, so the behaviour you're seeing is intentional. If you're looking for premade quests, there are multiple modpacks that offer them.
