### ISSUE TITLE
[Crash] Occasional Crashes 

### ISSUE THREAD

**Issue by jmadarg** [WinterWolfSV/Cobblemon_Quests#5]
On a [BigChadGuys+](https://legacy.curseforge.com/minecraft/modpacks/bigchadguys-plus/files/5082680) server there are occasional crashes.

We still don't know what triggers them, but they are becoming more frequent.

This is the crash report https://mclo.gs/s7mQ0cr

`java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbquests.quest.ServerQuestFile.getOrCreateTeamData(dev.ftb.mods.ftbteams.api.Team)" because "dev.ftb.mods.ftbquests.quest.ServerQuestFile.INSTANCE" is null`

**Comment by WinterWolfSV** [comment]
Hello! I apologise for the inconvenience. I believe to know the root of the issue and will work on a fix as soon as I'm back home. This means that I'll hopefully have a working release within the next two weeks. Do you by chance know in what situations this error occurrs? Is it when a normal player catches a pokemon or is it another mod that emulates a catch?

**Comment by jmadarg** [comment]
Sorry for the delay. The issue happens in a cluster of servers for BCG+ (4 servers with nearly 20 players reached regularly), but no player has come out saying it crashed when they catch a Pokemon, but it is probably because they think the crash is a coincidence. It's hard to actually know to be honest

**Comment by WinterWolfSV** [comment]
Hey! Sorry for not responding earlier, I've been chasing a connection over the past few days. What you mentioned would also explain why the crash happened, if there is no player to get the quest information from. If there is anyone on your team who knows how to program, and you don't want to wait ~1,5 weeks for me to fix it, you could pull the 1.1.7 version from commit [6cc0d1a](https://github.com/WinterWolfSV/Cobblemon_Quests/commit/6cc0d1a09f3f511fa07de04be0d549df87d28dbd) and inside the eventhandler class, surround all methods in try catches. This should prevent the server from crashing when this error occurs. This would also not require the mod to be changed on the client. Pulling from a later commit would require all players to update to 1.1.8 which has an incompatibility with the cobblebreeding mod. If this is not an option, I'll get a working release up and running when I'm back home.

**Comment by WinterWolfSV** [comment]
Hey again! The latest release now addresses the issue, it's up on modrinth and curseforge under the version 1.1.9.
