### ISSUE TITLE
Obtaining a Pokemon via the Resurrection Machine does not count it towards quest completion.

### ISSUE THREAD

**Issue by Lemenok** [WinterWolfSV/Cobblemon_Quests#8]
When the Resurrection Machine has finished growing a Pokemon, right clicking it with a poke ball does not count it towards the catch or Obtain actions.

**Comment by WinterWolfSV** [comment]
Hey! I haven't gotten to porting the mod to Cobblemon 1.5 yet, but I will update this issue when I get to it.

**Comment by WinterWolfSV** [comment]
Implemented in version 1.1.11
